### ISSUE TITLE
Request for codes

### ISSUE THREAD

**Issue by yuezhao-zy** [StalVars/CopyBERT#1]
Hi, you have done a great job.
Would you please share the codes of your paper? I find that you said you would share the codes before August?

**Comment by StalVars** [comment]
Hey All, I have been busy with  other deadlines. Thanks for your patience. I will do it in the next couple of weeks. And sorry for the delay.

**Comment by moon290** [comment]
Hi, I want to ask when the code will be shared？

**Comment by hongweizeng** [comment]
Any plans to share the codes?

**Comment by ghost** [comment]
I want ask the seam quesiton...

**Comment by vnik18** [comment]
Hi, please let me know if you plan to share the code?

**Comment by tushar117** [comment]
Hi @StalVars , please make the code available. It's been 2 yrs already.

**Comment by StalVars** [comment]
resolved
